name: "UmbHost Web Deploy"
description: "Deploy projects directly to UmbHost"
inputs:
  server-computer-name:
    description: "IIS server computer name (the IP of the server)"
    required: true
  server-username:
    description: "IIS server username (should also be the name of the app pool)"
    required: true
  server-password:
    description: "IIS server password"
    required: true
  source-path:
    description: "The source directory for payload"
    required: false
    default: '_build'
  source-paramFile:
    description: "The location of the SetParameters.xml file"
    required: true
    default: '""'
runs:
  using: "composite"
  steps:
    - name: Setting app into offline mode
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Set-AppOffline.ps1
        -username ${{ inputs.server-username }}
        -password "${{ inputs.server-password }}"
        -localDirectory ${{ github.workspace }}
        -serverAddress ${{ inputs.server-computer-name }}
    - name: Restarting the Application Pool
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Restart-ApplicationPool.ps1
        -recycleMode RecycleAppPool
        -computerName ${{ inputs.server-computer-name }}
        -username ${{ inputs.server-username }}
        -password "${{ inputs.server-password }}"
    - name: Deploy Application
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Deploy-ApplicationPackage.ps1
        -recycleApp ${{ inputs.website-name }}
        -computerName ${{ inputs.server-computer-name }}
        -username ${{ inputs.server-username }}
        -password "${{ inputs.server-password }}"
        -localDirectory ${{ github.workspace }}
    - name: Remove app offline
      shell: pwsh
      run: >
        ${{ github.action_path }}/Scripts/Remove-AppOffline.ps1
        -computerName ${{ inputs.server-computer-name }}
        -username ${{ inputs.server-username }}
        -password "${{ inputs.server-password }}"
branding:
  icon: 'server'
  color: 'blue'
